// omega-gate/proposals.ts
// Persist proposals to pulse_proposals for human review.

import { randomUUID } from "crypto";
import { getSupabase } from "../supabase.js";
import type { GateHeaders, GateRequest } from "./validation.js";
import type { ExecutionResult } from "./executor.js";

/**
 * Persist a proposal generated by a propose tool.
 * Returns the proposal UUID.
 */
export async function persistProposal(
  headers: GateHeaders,
  request: GateRequest,
  effectPreRef: string,
  result: ExecutionResult
): Promise<string> {
  const proposalId = randomUUID();

  try {
    const { error } = await getSupabase().from("pulse_proposals").insert({
      id: proposalId,
      call_id: request.call_id,
      tool: request.tool,
      scope: headers.scope,
      agent: headers.agent,
      intent: request.intent,
      inputs: request.inputs,
      status: "pending",
      verdict: "require_human",
      effect_pre_ref: effectPreRef,
      execution_result: {
        summary: result.summary,
        artifacts: result.artifacts,
      },
    });

    if (error) {
      console.error("[omega-gate] Failed to persist proposal:", error.message);
    }
  } catch (err) {
    // Proposal persistence failure must not block the gate response
    console.error("[omega-gate] Proposal write error:", err);
  }

  return proposalId;
}
