// lib/simulation/server/fixPlan.ts
import "server-only";

import { makeRequestId, simLog } from "@/lib/simulation/server/log";

// ✅ Server-side kernel entrypoint (adjust import if your kernel is exported differently)
import { agiKernel } from "@/lib/agi/kernel";

export type FixPlanInput = {
  userId: string;
  run: any; // full simulation_runs row (including input/result/error)
  step: {
    id: string;
    title: string;
    ok: boolean;
    severity?: string | null;
    detail?: string | null;
    pathId?: string | null;
    data?: any;
  };
};

export type FixPlanOutput = {
  request_id: string;
  plan_markdown: string;
  patch_json: any | null;
};

/**
 * Generates a fix plan using AGI kernel.
 * If kernel fails, returns a deterministic fallback plan.
 */
export async function generateFixPlan(input: FixPlanInput): Promise<FixPlanOutput> {
  const request_id = makeRequestId();
  const log = simLog(request_id);

  const { userId, run, step } = input;

  log.info("fixplan.start", {
    run_id: run?.id,
    step_id: step.id,
    step_title: step.title,
  });

  const context = {
    run: {
      id: run?.id,
      request_id: run?.request_id,
      route: run?.route,
      mode: run?.mode,
      deal_id: run?.deal_id,
      path_ids: run?.path_ids,
      status: run?.status,
      error: run?.error,
      duration_ms: run?.duration_ms,
      started_at: run?.started_at,
      finished_at: run?.finished_at,
      input: run?.input ?? {},
      result: run?.result ?? {},
    },
    failed_step: {
      id: step.id,
      title: step.title,
      ok: step.ok,
      severity: step.severity ?? null,
      pathId: step.pathId ?? null,
      detail: step.detail ?? null,
      data: step.data ?? null,
    },
  };

  // 1) Try AGI kernel
  try {
    log.info("fixplan.kernel.call");
    const kernelOut = await agiKernel.run({
      userId,
      intent: "simulation.fixplan.v1",
      input: context,
    });

    // Expect either:
    // - { plan_markdown, patch_json }
    // - or anything convertible
    const plan_markdown =
      (typeof kernelOut?.plan_markdown === "string" && kernelOut.plan_markdown) ||
      (typeof kernelOut?.markdown === "string" && kernelOut.markdown) ||
      fallbackMarkdown(context);

    const rawPatch = kernelOut?.patch_json ?? kernelOut?.patch ?? null;

    const patch_json = normalizePatchV1(rawPatch);

    log.info("fixplan.kernel.ok", { has_patch: !!patch_json });
    return { request_id, plan_markdown, patch_json };
  } catch (e: any) {
    log.error("fixplan.kernel.error", { error: e?.message || String(e) });
    // 2) Deterministic fallback
    return {
      request_id,
      plan_markdown: fallbackMarkdown(context),
      patch_json: null,
    };
  }
}

function fallbackMarkdown(ctx: any): string {
  const step = ctx.failed_step;
  const run = ctx.run;

  return [
    `# Fix Plan (Fallback)`,
    ``,
    `## What failed`,
    `- **Run**: ${run.request_id} (${run.route})`,
    `- **Step**: ${step.id} — ${step.title}`,
    step.detail ? `- **Detail**: ${step.detail}` : `- **Detail**: (none)`,
    ``,
    `## Most likely causes`,
    `1) Contract mismatch (unexpected payload shape)`,
    `2) Missing env var / auth context on server route`,
    `3) Server-only module imported from client (boundary regression)`,
    `4) Database missing migration/table/column referenced by the step`,
    ``,
    `## Verification checklist`,
    `- Re-run this exact run from the UI (Re-run button)`,
    `- Open the run details → inspect **failed step data** JSON`,
    `- Check server logs by request_id: **${run.request_id}** (original)`,
    ``,
    `## Minimal patch plan (generic)`,
    `1) Locate the code path producing this step (search for the step title / pathId)`,
    `2) Validate the input/output contracts and add Zod guards at boundaries`,
    `3) If DB-related: confirm migrations applied + table/columns exist`,
    `4) Add a deterministic unit test / simulation scenario that reproduces the failure`,
    ``,
    `## Regression tests`,
    `- npm run build`,
    `- npm test (if present)`,
    `- Run Simulation scenario again + confirm audit status=success`,
    ``,
  ].join("\n");
}

function normalizePatchV1(raw: any) {
  if (!raw || typeof raw !== "object") return null;

  // If it already matches our schema shape, keep it.
  if (raw.version === "patch.v1" && Array.isArray(raw.ops)) return raw;

  // If model returns { files: [{path, content}] } convert it
  if (Array.isArray(raw.files)) {
    return {
      version: "patch.v1",
      summary: raw.summary || "Autogenerated patch",
      ops: raw.files.map((f: any) => ({
        op: "upsert",
        path: String(f.path || ""),
        content: String(f.content || ""),
        note: f.note ? String(f.note) : undefined,
      })),
    };
  }

  // If model returns a single op-like object
  if (raw.op && raw.path) {
    return {
      version: "patch.v1",
      summary: raw.summary || "Autogenerated patch",
      ops: [raw],
    };
  }

  return null;
}

