import fs from "fs";
import path from "path";

const ROOT = process.cwd();

function exists(p) {
    try {
        return fs.existsSync(p);
    } catch {
        return false;
    }
}

// ✅ Supports both common layouts:
// 1) app/** (root)
// 2) src/app/** (Next.js monorepo-ish / src layout)
const APP_DIR = exists(path.join(ROOT, "src", "app"))
    ? path.join(ROOT, "src", "app")
    : path.join(ROOT, "app");

const OUT_DIR = path.join(ROOT, "lib", "generated");

function walk(dir) {
    const out = [];
    if (!exists(dir)) return out;
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, ent.name);
        if (ent.isDirectory()) out.push(...walk(p));
        else out.push(p);
    }
    return out;
}

function normalizeSlashes(p) {
    return p.replace(/\\/g, "/");
}

function stripAppPrefix(file) {
    return normalizeSlashes(path.relative(APP_DIR, file));
}

function toUrlFromPage(rel) {
    if (!rel.endsWith("/page.tsx")) return null;
    let url = "/" + rel.replace(/\/page\.tsx$/, "");

    // Remove route groups: /(group)/
    url = url.replace(/\/\([^/]+\)/g, "");

    // Remove parallel segments: /@slot
    url = url.replace(/\/@[^/]+/g, "");

    url = url.replace(/\/+/g, "/");
    return url === "/page" ? "/" : url;
}

function toUrlFromApi(rel) {
    if (!rel.startsWith("api/")) return null;
    if (!rel.endsWith("/route.ts")) return null;

    let url = "/" + rel.replace(/\/route\.ts$/, "");
    url = url.replace(/\/\([^/]+\)/g, "");
    url = url.replace(/\/@[^/]+/g, "");
    url = url.replace(/\/+/g, "/");
    return url;
}

function ensureDir(p) {
    fs.mkdirSync(p, { recursive: true });
}

function writeGenerated(filePath, content) {
    ensureDir(path.dirname(filePath));
    fs.writeFileSync(filePath, content, "utf8");
}

function tsArrayExport(name, items, appRootHint) {
    const body = items.map((x) => `  "${x}",`).join("\n");
    return `// AUTO-GENERATED by scripts/generate-routes.mjs. DO NOT EDIT MANUALLY.
// App root detected: ${appRootHint}
export const ${name} = [
${body}
] as const;
`;
}

const allFiles = walk(APP_DIR).map((f) => normalizeSlashes(f));

// Pages
const pageFiles = allFiles.filter((f) => f.endsWith("/page.tsx"));
const pageUrls = pageFiles
    .map((f) => toUrlFromPage(stripAppPrefix(f)))
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));

// APIs
const apiFiles = allFiles.filter((f) => f.endsWith("/route.ts") && f.includes("/api/"));
const apiUrls = apiFiles
    .map((f) => toUrlFromApi(stripAppPrefix(f)))
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));

writeGenerated(
    path.join(OUT_DIR, "pages.ts"),
    tsArrayExport("GENERATED_PAGES", pageUrls, normalizeSlashes(path.relative(ROOT, APP_DIR)))
);
writeGenerated(
    path.join(OUT_DIR, "apis.ts"),
    tsArrayExport("GENERATED_APIS", apiUrls, normalizeSlashes(path.relative(ROOT, APP_DIR)))
);

console.log(`App root: ${APP_DIR}`);
console.log(`Generated pages: ${pageUrls.length}`);
console.log(`Generated apis: ${apiUrls.length}`);
console.log("Wrote lib/generated/pages.ts and lib/generated/apis.ts");
