-- Email Resolution Overlay (NO provider assumptions)

create table if not exists public.email_resolution (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  email_thread_id uuid not null,
  state text not null, -- needs_user_action | waiting_on_other | scheduled_follow_up | converted_to_task | resolved
  why text not null,
  evidence jsonb not null default '[]'::jsonb,
  next_action_at timestamptz null,
  linked_task_id uuid null,
  confidence integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists email_resolution_user_idx
  on public.email_resolution(user_id, state);

create index if not exists email_resolution_next_action_idx
  on public.email_resolution(user_id, next_action_at)
  where next_action_at is not null;

-- Unique constraint: one resolution per thread per user
create unique index if not exists email_resolution_user_thread_unique
  on public.email_resolution(user_id, email_thread_id);

-- Drafts generated by Pulse

create table if not exists public.email_drafts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  email_thread_id uuid not null,
  subject text null,
  body_text text not null,
  intent text not null, -- confirm | decline | buy_time | ask | commit | close
  evidence jsonb not null default '[]'::jsonb,
  status text not null default 'draft', -- draft | approved | sent
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Follow-ups Pulse owns

create table if not exists public.email_followups (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  email_thread_id uuid not null,
  due_at timestamptz not null,
  note text null,
  state text not null default 'open',
  created_at timestamptz not null default now()
);

-- updated_at trigger

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_email_resolution_updated_at on public.email_resolution;
create trigger trg_email_resolution_updated_at
before update on public.email_resolution
for each row execute function public.set_updated_at();

drop trigger if exists trg_email_drafts_updated_at on public.email_drafts;
create trigger trg_email_drafts_updated_at
before update on public.email_drafts
for each row execute function public.set_updated_at();

