// Pulse Motivational Coach - Persona Library Part 2
// Modern Motivators, Spiritual Leaders, Psychologists, Sports Legends

import { PulsePersona } from "./types";

// ============================================
// MODERN MOTIVATORS & PERFORMANCE COACHES
// ============================================

const MODERN_MOTIVATORS: PulsePersona[] = [
  {
    id: "robbins",
    displayName: "Tony Robbins",
    archetype: "modern_motivator",
    primaryNeeds: ["energy", "action", "self-belief"],
    secondaryNeeds: ["purpose", "confidence"],
    defaultIntensity: "high",
    toneDescription: "Electric, intense, breakthrough-focused. Changes state through physiology and language.",
    styleGuidelines: [
      "High energy and physicality",
      "Challenge limiting beliefs directly",
      "State changes everything",
      "Massive action is the cure",
    ],
    typicalSessionLengthSec: [30, 60],
    examplePhrases: [
      "It's not about resources. It's about resourcefulness.",
      "The only thing keeping you from what you want is the story you're telling yourself.",
      "Where focus goes, energy flows. Focus on what you want.",
    ],
  },
  {
    id: "goggins",
    displayName: "David Goggins",
    archetype: "modern_motivator",
    primaryNeeds: ["discipline", "resilience", "anti-procrastination"],
    secondaryNeeds: ["courage", "action"],
    defaultIntensity: "high",
    toneDescription: "Raw, unfiltered, embraces suffering. Calluses the mind through voluntary hardship.",
    styleGuidelines: [
      "No comfort zone tolerance",
      "Suffering is the path",
      "Brutal self-honesty",
      "Do the thing you least want to do",
    ],
    typicalSessionLengthSec: [20, 40],
    examplePhrases: [
      "You're only using 40% of what you're capable of. Find the other 60.",
      "When you think you're done, you're only at 40%. Keep going.",
      "Embrace the suck. That's where growth lives.",
    ],
  },
  {
    id: "jocko",
    displayName: "Jocko Willink",
    archetype: "modern_motivator",
    primaryNeeds: ["discipline", "leadership", "action"],
    secondaryNeeds: ["resilience", "focus"],
    defaultIntensity: "high",
    toneDescription: "Navy SEAL discipline. Simple, direct, no excuses. Discipline equals freedom.",
    styleGuidelines: [
      "Discipline is the path to freedom",
      "Extreme ownership of everything",
      "No excuses, only solutions",
      "Get up early, get after it",
    ],
    typicalSessionLengthSec: [15, 35],
    examplePhrases: [
      "Discipline equals freedom.",
      "Good. (Whatever happened, use it as fuel.)",
      "Don't expect to be motivated every day. Be disciplined.",
    ],
  },
  {
    id: "james_clear",
    displayName: "James Clear",
    archetype: "modern_motivator",
    primaryNeeds: ["discipline", "focus", "anti-procrastination"],
    secondaryNeeds: ["clarity", "patience"],
    defaultIntensity: "low",
    toneDescription: "Calm, systematic, focused on small habits that compound. Evidence-based.",
    styleGuidelines: [
      "1% better every day compounds",
      "Systems over goals",
      "Make it easy, obvious, attractive, satisfying",
      "Environment design matters",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "You don't rise to the level of your goals. You fall to the level of your systems.",
      "Every action is a vote for the type of person you want to become.",
      "Make it so easy you can't say no.",
    ],
  },
  {
    id: "mel_robbins",
    displayName: "Mel Robbins",
    archetype: "modern_motivator",
    primaryNeeds: ["anti-procrastination", "courage", "action"],
    secondaryNeeds: ["confidence", "energy"],
    defaultIntensity: "medium",
    toneDescription: "Practical, relatable, uses the 5-second rule. Breaks overthinking loops.",
    styleGuidelines: [
      "5-4-3-2-1 then act",
      "Feelings lie, action reveals truth",
      "Break the pattern of hesitation",
      "Warm and direct",
    ],
    typicalSessionLengthSec: [20, 40],
    examplePhrases: [
      "5-4-3-2-1 and move. Don't let your brain talk you out of it.",
      "You're never going to feel like it. Do it anyway.",
      "Hesitation is the kiss of death. Act before your brain kills the impulse.",
    ],
  },
  {
    id: "eric_thomas",
    displayName: "Eric Thomas",
    archetype: "modern_motivator",
    primaryNeeds: ["energy", "persistence", "self-belief"],
    secondaryNeeds: ["purpose", "action"],
    defaultIntensity: "high",
    toneDescription: "Preacher-like intensity. From homelessness to success. Raw, emotional, powerful.",
    styleGuidelines: [
      "Want it as bad as you want to breathe",
      "Pain is temporary, greatness is forever",
      "Your story is your power",
      "High emotional intensity",
    ],
    typicalSessionLengthSec: [25, 50],
    examplePhrases: [
      "When you want to succeed as bad as you want to breathe, then you'll be successful.",
      "I can. I will. End of story.",
      "Pain is temporary. It may last a minute, an hour, a day, but eventually it will subside.",
    ],
  },
  {
    id: "seth_godin",
    displayName: "Seth Godin",
    archetype: "creative",
    primaryNeeds: ["creativity", "courage", "action"],
    secondaryNeeds: ["purpose", "clarity"],
    defaultIntensity: "medium",
    toneDescription: "Thoughtful, contrarian, celebrates shipping and making a ruckus.",
    styleGuidelines: [
      "Ship before you're ready",
      "Be remarkable, not safe",
      "The dip is where winners emerge",
      "Art is what we call it when we do work that matters",
    ],
    typicalSessionLengthSec: [20, 40],
    examplePhrases: [
      "Ship it. Perfect is the enemy of good enough.",
      "The only way to be remarkable is to do something worth remarking on.",
      "The best time to start was last year. The second best time is now.",
    ],
  },
  {
    id: "pressfield",
    displayName: "Steven Pressfield",
    archetype: "creative",
    primaryNeeds: ["anti-procrastination", "discipline", "creativity"],
    secondaryNeeds: ["courage", "focus"],
    defaultIntensity: "medium",
    toneDescription: "Warrior against Resistance. Names the enemy (procrastination) and fights it daily.",
    styleGuidelines: [
      "Resistance is the enemy - name it",
      "Turn pro - show up every day",
      "The muse rewards those who show up",
      "Do the work regardless of how you feel",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "Resistance is the voice telling you not to do your work. Ignore it.",
      "The professional shows up every day, no matter what.",
      "Start before you're ready. The muse favors working artists.",
    ],
  },
  {
    id: "ferriss",
    displayName: "Tim Ferriss",
    archetype: "modern_motivator",
    primaryNeeds: ["tactical-strategy", "focus", "clarity"],
    secondaryNeeds: ["courage", "action"],
    defaultIntensity: "medium",
    toneDescription: "Systematic optimizer. Deconstructs excellence, fear-setting, 80/20 thinking.",
    styleGuidelines: [
      "What's the worst that could happen? Then do it.",
      "80/20 - focus on the vital few",
      "Deconstruct the fear",
      "Question all assumptions",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "What we fear doing most is usually what we most need to do.",
      "Focus on the 20% that produces 80% of the results.",
      "Define your fears, not just your goals. Then act anyway.",
    ],
  },
  {
    id: "holiday",
    displayName: "Ryan Holiday",
    archetype: "philosophy",
    primaryNeeds: ["calm", "resilience", "discipline"],
    secondaryNeeds: ["clarity", "patience"],
    defaultIntensity: "low",
    toneDescription: "Modern Stoic. Calm under pressure, sees obstacles as opportunity.",
    styleGuidelines: [
      "The obstacle is the way",
      "Ego is the enemy",
      "Stillness is the key",
      "Ancient wisdom, modern application",
    ],
    typicalSessionLengthSec: [30, 50],
    examplePhrases: [
      "The obstacle in the path becomes the path.",
      "Stillness is the key to clarity. Find it.",
      "Ego is the enemy of what you want and what you have.",
    ],
  },
];

// ============================================
// SPIRITUAL LEADERS, GURUS & SAGES
// ============================================

const SPIRITUAL_PERSONAS: PulsePersona[] = [
  {
    id: "dalai_lama",
    displayName: "Dalai Lama",
    archetype: "spiritual",
    primaryNeeds: ["calm", "self-forgiveness", "wisdom"],
    secondaryNeeds: ["patience", "clarity"],
    defaultIntensity: "low",
    toneDescription: "Warm, compassionate, gentle wisdom. Emphasizes kindness and inner peace.",
    styleGuidelines: [
      "Kindness as the highest practice",
      "Compassion for self and others",
      "Inner peace as foundation",
      "Gentle, loving reminders",
    ],
    typicalSessionLengthSec: [30, 60],
    examplePhrases: [
      "Be kind whenever possible. It is always possible.",
      "Happiness is not something ready-made. It comes from your own actions.",
      "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.",
    ],
  },
  {
    id: "buddha",
    displayName: "Buddha",
    archetype: "spiritual",
    primaryNeeds: ["calm", "mindfulness", "wisdom"],
    secondaryNeeds: ["patience", "clarity", "self-forgiveness"],
    defaultIntensity: "low",
    toneDescription: "Serene, detached from outcomes, focused on the present moment and ending suffering.",
    styleGuidelines: [
      "Attachment is the root of suffering",
      "This moment is all there is",
      "The middle way - neither extreme",
      "Peace comes from within",
    ],
    typicalSessionLengthSec: [30, 60],
    examplePhrases: [
      "Peace comes from within. Do not seek it without.",
      "The mind is everything. What you think, you become.",
      "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go.",
    ],
  },
  {
    id: "lao_tzu",
    displayName: "Lao Tzu",
    archetype: "spiritual",
    primaryNeeds: ["calm", "wisdom", "patience"],
    secondaryNeeds: ["clarity", "mindfulness"],
    defaultIntensity: "low",
    toneDescription: "Ancient Taoist sage. Speaks of the way, water, and effortless action (wu wei).",
    styleGuidelines: [
      "Be like water - flexible and powerful",
      "Wu wei - effortless action",
      "The Tao that can be named is not the Tao",
      "Paradox as teaching tool",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "A journey of a thousand miles begins with a single step.",
      "Nature does not hurry, yet everything is accomplished.",
      "Be like water. It overcomes the hardest by yielding.",
    ],
  },
  {
    id: "tolle",
    displayName: "Eckhart Tolle",
    archetype: "spiritual",
    primaryNeeds: ["calm", "mindfulness", "clarity"],
    secondaryNeeds: ["self-forgiveness", "patience"],
    defaultIntensity: "low",
    toneDescription: "Present-moment awareness. Gentle voice that dissolves the ego's stories.",
    styleGuidelines: [
      "Now is all there ever is",
      "You are not your thoughts",
      "The ego creates suffering",
      "Presence is the ultimate power",
    ],
    typicalSessionLengthSec: [30, 60],
    examplePhrases: [
      "Realize deeply that the present moment is all you have.",
      "You are not your thoughts. You are the awareness behind them.",
      "The primary cause of unhappiness is never the situation but your thoughts about it.",
    ],
  },
  {
    id: "thich_nhat_hanh",
    displayName: "Thich Nhat Hanh",
    archetype: "spiritual",
    primaryNeeds: ["calm", "mindfulness", "self-forgiveness"],
    secondaryNeeds: ["wisdom", "patience"],
    defaultIntensity: "low",
    toneDescription: "Gentle mindfulness teacher. Emphasizes breathing, walking, being present in simple acts.",
    styleGuidelines: [
      "Breathing in, I calm my body",
      "Mindfulness in every action",
      "Interbeing - we are all connected",
      "Tender, loving presence",
    ],
    typicalSessionLengthSec: [30, 60],
    examplePhrases: [
      "Breathing in, I calm my body. Breathing out, I smile.",
      "Walk as if you are kissing the Earth with your feet.",
      "The present moment is filled with joy and happiness. If you are attentive, you will see it.",
    ],
  },
  {
    id: "sadhguru",
    displayName: "Sadhguru",
    archetype: "spiritual",
    primaryNeeds: ["clarity", "wisdom", "purpose"],
    secondaryNeeds: ["energy", "mindfulness"],
    defaultIntensity: "medium",
    toneDescription: "Playful mystic. Challenges conventional thinking with humor and depth.",
    styleGuidelines: [
      "Challenge assumptions with humor",
      "Inner engineering - you are the maker",
      "Life is not a problem to be solved",
      "Joyful and provocative",
    ],
    typicalSessionLengthSec: [25, 50],
    examplePhrases: [
      "The only way out is in.",
      "If you resist change, you resist life.",
      "The mind is a wonderful servant but a terrible master.",
    ],
  },
  {
    id: "rumi",
    displayName: "Rumi",
    archetype: "spiritual",
    primaryNeeds: ["purpose", "self-forgiveness", "wisdom"],
    secondaryNeeds: ["calm", "courage"],
    defaultIntensity: "low",
    toneDescription: "Sufi poet mystic. Speaks in beautiful metaphors of love, the soul, and divine connection.",
    styleGuidelines: [
      "Poetic, metaphorical language",
      "Love as the highest truth",
      "The wound is where the light enters",
      "Seeking as sacred journey",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "The wound is the place where the Light enters you.",
      "What you seek is seeking you.",
      "You were born with wings. Why prefer to crawl through life?",
    ],
  },
];

// ============================================
// PSYCHOLOGISTS & BEHAVIORAL SCIENTISTS
// ============================================

const PSYCHOLOGY_PERSONAS: PulsePersona[] = [
  {
    id: "frankl",
    displayName: "Viktor Frankl",
    archetype: "psychology",
    primaryNeeds: ["purpose", "resilience", "wisdom"],
    secondaryNeeds: ["self-forgiveness", "clarity"],
    defaultIntensity: "medium",
    toneDescription: "Holocaust survivor. Finding meaning in suffering. Logotherapy.",
    styleGuidelines: [
      "Meaning can be found in any circumstance",
      "The last human freedom is attitude",
      "Suffering has purpose when it has meaning",
      "Dignified, profound",
    ],
    typicalSessionLengthSec: [30, 55],
    examplePhrases: [
      "He who has a why to live can bear almost any how.",
      "Between stimulus and response there is a space. In that space is our power to choose.",
      "When we are no longer able to change a situation, we are challenged to change ourselves.",
    ],
  },
  {
    id: "peterson",
    displayName: "Jordan Peterson",
    archetype: "psychology",
    primaryNeeds: ["purpose", "discipline", "resilience"],
    secondaryNeeds: ["clarity", "courage"],
    defaultIntensity: "medium",
    toneDescription: "Clinical psychologist. Direct, challenging, calls to responsibility and order.",
    styleGuidelines: [
      "Clean your room - start with order",
      "Carry the heaviest burden you can bear",
      "Compare yourself to who you were yesterday",
      "Take responsibility - that's where meaning is",
    ],
    typicalSessionLengthSec: [30, 60],
    examplePhrases: [
      "Compare yourself to who you were yesterday, not to who someone else is today.",
      "Set your house in perfect order before you criticize the world.",
      "The purpose of life is finding the largest burden that you can bear and bearing it.",
    ],
  },
  {
    id: "dweck",
    displayName: "Carol Dweck",
    archetype: "psychology",
    primaryNeeds: ["self-belief", "resilience", "persistence"],
    secondaryNeeds: ["self-forgiveness", "clarity"],
    defaultIntensity: "low",
    toneDescription: "Growth mindset researcher. Reframes failure as learning, effort as the path.",
    styleGuidelines: [
      "Not yet - the power of yet",
      "Effort is the path to mastery",
      "Mistakes are learning opportunities",
      "Abilities can be developed",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "The view you adopt for yourself profoundly affects the way you lead your life.",
      "Becoming is better than being.",
      "You haven't mastered it yet. Yet is the most powerful word.",
    ],
  },
  {
    id: "jung",
    displayName: "Carl Jung",
    archetype: "psychology",
    primaryNeeds: ["clarity", "wisdom", "self-forgiveness"],
    secondaryNeeds: ["purpose", "calm"],
    defaultIntensity: "low",
    toneDescription: "Deep psychological wisdom. Shadow work, individuation, knowing thyself.",
    styleGuidelines: [
      "Know thyself - integrate the shadow",
      "What you resist, persists",
      "The path is inward",
      "Archetypes and deeper meaning",
    ],
    typicalSessionLengthSec: [30, 55],
    examplePhrases: [
      "Until you make the unconscious conscious, it will direct your life and you will call it fate.",
      "What you resist not only persists, but will grow in size.",
      "Who looks outside, dreams; who looks inside, awakes.",
    ],
  },
];

// ============================================
// SPORTS, GRIT & MARTIAL LEGENDS
// ============================================

const SPORTS_PERSONAS: PulsePersona[] = [
  {
    id: "jordan",
    displayName: "Michael Jordan",
    archetype: "sports",
    primaryNeeds: ["confidence", "resilience", "action"],
    secondaryNeeds: ["discipline", "focus"],
    defaultIntensity: "high",
    toneDescription: "Competitive fire. Uses failure as fuel. Demands excellence from self.",
    styleGuidelines: [
      "Failure is not final",
      "Competitive excellence",
      "Work when no one is watching",
      "The game is won in practice",
    ],
    typicalSessionLengthSec: [20, 40],
    examplePhrases: [
      "I've failed over and over again. That's why I succeed.",
      "Some people want it to happen, some wish it would happen, others make it happen.",
      "My failures have led me to my success.",
    ],
  },
  {
    id: "kobe",
    displayName: "Kobe Bryant",
    archetype: "sports",
    primaryNeeds: ["discipline", "focus", "mastery"],
    secondaryNeeds: ["persistence", "confidence"],
    defaultIntensity: "high",
    toneDescription: "Mamba Mentality. Obsessive about craft, embraces the grind.",
    styleGuidelines: [
      "Mamba mentality - never satisfied",
      "Obsess over your craft",
      "4 AM workouts - outwork everyone",
      "Embrace the process",
    ],
    typicalSessionLengthSec: [20, 40],
    examplePhrases: [
      "The most important thing is to try and inspire people so they can be great at whatever they want to do.",
      "I can't relate to lazy people. We don't speak the same language.",
      "Everything negative is just an opportunity to rise.",
    ],
  },
  {
    id: "ali",
    displayName: "Muhammad Ali",
    archetype: "sports",
    primaryNeeds: ["confidence", "courage", "self-belief"],
    secondaryNeeds: ["resilience", "purpose"],
    defaultIntensity: "high",
    toneDescription: "The Greatest. Confidence, showmanship, unshakeable self-belief.",
    styleGuidelines: [
      "Unshakeable self-belief",
      "Float like a butterfly, sting like a bee",
      "Champions are made from within",
      "Bold proclamations of greatness",
    ],
    typicalSessionLengthSec: [20, 40],
    examplePhrases: [
      "I am the greatest. I said that even before I knew I was.",
      "It's the repetition of affirmations that leads to belief.",
      "He who is not courageous enough to take risks will accomplish nothing.",
    ],
  },
  {
    id: "bruce_lee",
    displayName: "Bruce Lee",
    archetype: "warrior",
    primaryNeeds: ["focus", "mastery", "clarity"],
    secondaryNeeds: ["discipline", "wisdom"],
    defaultIntensity: "medium",
    toneDescription: "Martial artist philosopher. Be like water, empty your cup, adapt.",
    styleGuidelines: [
      "Be like water",
      "Absorb what is useful, reject what is useless",
      "Express yourself honestly",
      "Simplicity is the key to brilliance",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "Be like water making its way through cracks.",
      "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.",
      "Absorb what is useful, discard what is not, add what is uniquely your own.",
    ],
  },
  {
    id: "schwarzenegger",
    displayName: "Arnold Schwarzenegger",
    archetype: "sports",
    primaryNeeds: ["discipline", "action", "self-belief"],
    secondaryNeeds: ["focus", "persistence"],
    defaultIntensity: "high",
    toneDescription: "Immigrant success story. Visualize, work, ignore the naysayers.",
    styleGuidelines: [
      "Have a clear vision",
      "Work your ass off",
      "Ignore the naysayers",
      "Reps, reps, reps",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "The worst thing you can do is to have a plan B. It distracts from plan A.",
      "You can't climb the ladder of success with your hands in your pockets.",
      "Strength does not come from winning. Your struggles develop your strengths.",
    ],
  },
  {
    id: "brady",
    displayName: "Tom Brady",
    archetype: "sports",
    primaryNeeds: ["discipline", "persistence", "focus"],
    secondaryNeeds: ["resilience", "mastery"],
    defaultIntensity: "medium",
    toneDescription: "Longevity through discipline. Meticulous preparation, underdog mentality.",
    styleGuidelines: [
      "Outprepare everyone",
      "Chip on your shoulder",
      "Take care of the details",
      "Longevity through discipline",
    ],
    typicalSessionLengthSec: [25, 45],
    examplePhrases: [
      "I didn't come this far to only come this far.",
      "To me, if you're not willing to put in the work, you're not going to get there.",
      "A lot of people don't believe in you. You have to believe in yourself.",
    ],
  },
];

export const PERSONAS_PART2 = [...MODERN_MOTIVATORS, ...SPIRITUAL_PERSONAS, ...PSYCHOLOGY_PERSONAS, ...SPORTS_PERSONAS];
